### ISSUE TITLE
vstools set_output broken for AudioNodes

### ISSUE THREAD

**Issue by jsaowji** [Jaded-Encoding-Thaumaturgy/vs-preview#181]
```py
from vstools import core,set_output

set_output(core.std.BlankAudio())
```
```
Traceback (most recent call last):
  File "/tmp/rr.py", line 3, in <module>
    set_output(core.std.BlankAudio())
  File "/home/user/git/jet/vs-tools/vstools/utils/misc.py", line 437, in set_output
    vsp_set_output(node, name, alpha, **kwargs)
  File "/home/user/git/jet/vs-preview/vspreview/api/output.py", line 56, in set_output
    node.set_output(index, alpha)
  File "src/cython/vapoursynth.pyx", line 2451, in vapoursynth.AudioNode.set_output
TypeError: set_output() takes at most 1 positional argument (2 given)
```
vstools set_output broken for AudioNodes by presumebly
https://github.com/Jaded-Encoding-Thaumaturgy/vs-preview/commit/732627d0aa9dd74e87c7486bc52296b420e61249
https://github.com/Jaded-Encoding-Thaumaturgy/vs-tools/commit/1ae8f44910169a0600455c16b2873d2a2d5e6655

**Comment by YomikoR** [comment]
#136

**Comment by jsaowji** [comment]
unrelated issue happens with vspipe too. Opend here and not in vs-tools because crash is here.
